Spring:
  dataSource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/easybuy?useUnicode=true&characterEncoding=utf-8
    username: root
    password: jt99123
mybatis:
  config-location: classpath:mybatis.xml